# NOTE: all services use the `web` network in order to overcome mtu
# limitations. The `web` network has mtu:1400
#

x-common-networks: &common-networks
  networks:
    - web


services:
  django:
    image: ghcr.io/gisdevio/tools4msp-geoplatform:${GEOPLATFORM_IMAGE_VERSION}
    build: !reset null
    <<: *common-networks

  celery:
    image: ghcr.io/gisdevio/tools4msp-geoplatform:${GEOPLATFORM_IMAGE_VERSION}
    <<: *common-networks

  geonode:
    ports: !reset []
    labels:
      traefik.enable: true
      traefik.http.routers.tools4msp_geoplatform_geonode_router.rule: Host(`dev.geoplatform.tools4msp.eu`)
      traefik.http.routers.tools4msp_geoplatform_geonode_router.tls.certresolver: le
      traefik.http.routers.tools4msp_geoplatform_geonode_router.entrypoints: websecure
    volumes:
      - type: bind
        source: $PWD/geonode.conf.envsubst
        target: /etc/nginx/sites-enabled/geonode.conf.envsubst
        read_only: true
    <<: *common-networks

  memcached:
    <<: *common-networks

  geoserver:
    ports: !reset []
    <<: *common-networks

  data-dir-conf:
    <<: *common-networks

  db:
    <<: *common-networks

  rabbitmq:
    <<: *common-networks


networks:
  web:
    external: true
    name: traefik_tools4msp_geoplatform_webgateway
