# Generated by Django 3.2.23 on 2024-04-27 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '0044_alter_dataset_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoDataBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('desc_expression', models.TextField(help_text='an Expression... HELP', max_length=2000, verbose_name='expression description')),
                ('expression', models.TextField(blank=True, help_text='an Expression... HELP', max_length=2000, null=True, verbose_name='expression')),
                ('expression_id_string', models.TextField(blank=True, help_text='an Expression... HELP', max_length=2000, null=True, verbose_name='expression id')),
                ('file_path', models.CharField(blank=True, max_length=2000, null=True, verbose_name='file')),
                ('file_updated', models.DateTimeField(blank=True, null=True, verbose_name='file data update')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='date when expression were last updated', verbose_name='last modified')),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_geodatabuilder', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name_plural': 'GeoDataBuilders',
                'ordering': ('label', 'created', 'updated'),
            },
        ),
        migrations.CreateModel(
            name='GeoDataBuilderVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attribute', models.CharField(blank=True, max_length=255, null=True)),
                ('where_condition', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('geodatabuilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='geodatabuilder.geodatabuilder')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layers.dataset')),
            ],
        ),
    ]
