# Generated by Django 2.2.24 on 2022-08-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodatabuilder', '0010_geodatabuildervariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodatabuildervariable',
            name='attribute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geodatabuildervariable',
            name='geodatabuilder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='geodatabuilder.GeoDataBuilder'),
        ),
    ]
