# Generated by Django 2.2.24 on 2022-08-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodatabuilder', '0011_auto_20220826_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodatabuilder',
            name='expression',
            field=models.TextField(blank=True, help_text='an Expression... HELP', max_length=2000, null=True, verbose_name='expression'),
        ),
        migrations.AlterField(
            model_name='geodatabuilder',
            name='expression_id_string',
            field=models.TextField(blank=True, help_text='an Expression... HELP', max_length=2000, null=True, verbose_name='expression id'),
        ),
    ]
