# Generated by Django 2.2.24 on 2022-10-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0002_auto_20221021_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools4MSPOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('group', models.CharField(max_length=250)),
            ],
        ),
    ]
