name: Tools4MSP Geoplatform CI

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  docker-build:
    name: Build Docker

    runs-on: ubuntu-latest

    steps:
      - name: Prepare image
        id: prepare-image
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> "${GITHUB_ENV}"
          DOCKER_IMAGE=ghcr.io/${OWNER}/tools4msp-geoplatform
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            VERSION=$(echo ${VERSION} | sed s/^v//)
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            VERSION=latest
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=image::${DOCKER_IMAGE}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.prepare-image.outputs.tags }}
